### ISSUE TITLE
Replacement char is cut off

### ISSUE THREAD

**Issue by iTitus** [phip1611/noto-sans-mono-bitmap-rs#15]
The replacement char (`0xfffd` / `�`) is cut off.
Working render: ![image](https://github.com/phip1611/noto-sans-mono-bitmap-rs/assets/5154317/a1b7cc5a-2690-4b00-a262-23f67e59d82a)
Replacement character: ![image](https://github.com/phip1611/noto-sans-mono-bitmap-rs/assets/5154317/cc4a4e8f-f4df-41cf-b8ce-6fb5efddaad5)

**Comment by phip1611** [comment]
Hi! I'm aware of the problem and it's a similar problem to <https://github.com/phip1611/noto-sans-mono-bitmap-rs/issues/14>

I don't know how to solve this properly so that the problem is fixed for all characters in all font sizes :/

Problem must be addressed somewhere here:
- https://github.com/phip1611/noto-sans-mono-bitmap-rs/blob/main/codegen/src/font.rs#L145
- https://github.com/phip1611/noto-sans-mono-bitmap-rs/blob/main/codegen/src/font.rs#L172

**Comment by phip1611** [comment]
Can't really fix it, unfortunately. The current solution is IMHO good enough for what it is. 

As the README says, the use case of this library is limited anyway.

More info: https://github.com/phip1611/noto-sans-mono-bitmap-rs/pull/17
